<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Report testing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ca00754c-3883-4b9d-b657-4bedc5313294</testSuiteGuid>
   <testCaseLink>
      <guid>f869cf77-d1b5-4135-a3ef-7b47472a1696</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Fixed_Value_exist in the  system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c73e33b-26ed-403b-9a7e-29a47870a7a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9463e630-892d-48b5-8ead-d8bd5719c4c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9829c949-1e6a-4703-8d19-a55a6dc57a4d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0facaa2c-1b67-4a33-8aba-8f7d4fc81dbf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Fixed_Value_Variables_exist_in_the_System</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fa89983-a475-4361-8025-90c9cd13d877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>641c81ed-68d9-462a-bc2f-da81f151542c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26fa0d92-1c87-46bd-8f16-e89d617166f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5ae30db-d729-4138-9c80-7b6190d235af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Formulas exits in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0a66b4d-7999-4ee9-8189-ba68069eff7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>def9cb60-d9c0-4de0-922e-693d96ff7777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0f00ec6-e549-4bb9-92b0-666375d1d80a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa967b81-4fdd-4cc9-9437-5c2199cf18fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Lookup_Tables_exist_in_the_system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fdfe7ef-ed30-400b-832c-f2143b7bfa48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>182c6b7e-9a09-492e-b00b-928edbc298d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d4bc9f-f6e7-445e-8591-0da072058e4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90d70377-62ac-4439-bf3f-fa99726a54d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Lookup_Table_Varaibles_exist_in_the_system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70ccc00d-1382-4257-887f-0f38cebf8422</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f86f539-ca9f-404f-89c3-6d489029c3ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a183563e-a5e4-4387-b2b8-2543be43ed5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11e2cff7-7dbb-46b0-ba5c-8dd8c7900eba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Quotas exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d13179cd-4be8-4b92-a7c9-b19e86d3309a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d145add3-dbe2-424a-933e-2867919d4f32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd6a2039-fdbb-45b1-953c-ca1803f8ae96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d4b3523-913f-4d40-a553-7504e70496cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Rate_Tables_exist_in_the_system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66f64c54-9083-410f-bd34-cafdd1b8bb15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92467eba-c232-4cdf-ae27-dcb076b27948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27057eab-723b-411c-ac9c-709038117014</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2abe2934-8a77-4fad-b4e3-a76f36853129</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Rate_Table_Variable_exist_in_the_system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd6e8f22-1107-4073-aa82-e568b9b1c9b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2c166d6-3d1e-48db-8c45-165be5091c90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57bded32-5ba9-4716-96b9-ff9a6d45eb7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d56b4bd-99c3-44f1-b959-3928c4876135</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Territory_Elements_exist_in_the_system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a494a9b-ceb2-4d6a-9872-04cf09c0c918</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c4d5aab-1b36-491d-a58a-ab9993ca910c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81c28cf0-b3fe-4a5f-826d-c271255fb6e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7359108-eb6c-44fd-9e48-e65101cdcc44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Compensation_Elements_Workspace/Territory_Variables_exist_in_the_system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df9cd5e8-a50d-411a-b5dd-cb35c50da836</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f67d9bba-ba9a-4b94-9999-ae68dc561f0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13aa4dd3-3e57-404b-b241-21fd628374ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afc79b13-03b3-4852-8931-3dc0dcb1a0be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Global_values_Workspace/Calendar_exist_in_the_system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df7a9a8e-8c22-45b4-b1dc-598e64a25266</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e6592f8-5e83-4286-a4f8-ef5eaa0e5868</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e338e19f-5ece-4396-b65a-30a20b95519a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Global_values_Workspace/Credit Type Exists in the System</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d10f5904-7efc-4026-99da-941cb043d242</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59ccd9bf-ad10-4547-a90c-6aac942e669e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a73cc4c-86a6-47fd-ac82-5ad0fa33f7e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2643e05-ae2c-43c7-ada5-466091bb7406</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Global_values_Workspace/Earning Codes exist in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b3347e0-c28a-4478-a55d-5f4381a5f6fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ef1cb62-cb24-4215-aa4f-8525182ba108</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe5ddd26-7f86-49bd-bcd3-926e2b4d4b70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f791db2-5af7-493c-9701-2bf5cc5223cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Global_values_Workspace/Earning Groups exist in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9826086b-e4be-4ead-9095-4bbbb2f90117</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8b63423-a90f-4098-8a65-162360718c91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1892726-f6a8-4e36-9e04-1d2741b18996</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5d0091e-929c-43bf-95f1-291f3e5cc477</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Global_values_Workspace/EventTypes exist in the System</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4160e49b-0720-494b-8e43-02a9252ebabc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cacba36-d52b-4d0c-909c-fa0b97031a4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33ede6fd-06f4-43e4-a076-e94d66cb0b7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bd8547f-0d2f-4292-84fc-6e8d56522555</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Global_values_Workspace/Fixed ValueTypes exist in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acdba550-ca59-4eb7-8adb-a440c6fc6ade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>452489dd-c8f6-4333-9b36-cff2e022017a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ca10c2-4b5c-4ef7-b9af-f5db25190b30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>558f6171-8a50-47a4-9aa8-ab36c3673cbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Global_values_Workspace/Position Groups exist in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3a2c5fa-44c4-4405-b18c-c374af9fc0c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>028d4f09-8681-437f-8a95-c0e5803f8b63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92096568-3bcb-4fd0-94bd-43b669091a50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c03032d9-cbda-4092-a179-3a9e8d417cdf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Global_values_Workspace/Reason_Codes exist in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb70221e-aa1a-42f9-9ea6-f620cb7b521d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a83c955-59e3-4680-8aca-bb3a8e74f8f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>005235bd-2465-4424-a157-9315d0189f87</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48dd6af3-059b-4c7e-b135-acb9f468a376</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Global_values_Workspace/UnitType exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f3201e0-3311-4b31-b667-fc25b9bc6f9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b81fb3d-30f8-49db-98f1-0f1ec26bb728</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d246692-fd60-45c3-8869-7328f8c19713</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c094f679-db81-43f9-849a-6da30fc6af7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Organization_workspace/Participants exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46a50384-5b5c-4d30-90b2-ba093b8e8c9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0e026dc-55a3-479c-8e2b-bd9f20e23bc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bca68da-6b4d-4983-ad49-ce7430d870a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1584846-b282-4171-b5ec-d330a42a169f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Organization_workspace/Positions exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aae27e85-7c39-44d2-a46f-1688ba8f2472</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ad60a7e-58e2-493b-8ab4-2be212ae0df2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>301eb381-a0c4-481d-a20a-af714d617820</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec12a403-3708-4e3a-9b85-bd9eddda6817</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Organization_workspace/Relationship_exist_in_the_system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64824454-206f-471c-8464-85580e2b3bc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d14ea889-b6e1-46a4-8a4c-730283be276e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>562aefaf-d887-45f2-b34b-1b30b1ee928a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9de3095c-3339-424a-9328-c807cd54e7fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97501fbe-972f-42e0-a133-fc00b01e2449</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7b70861-bcfc-4673-91aa-46ba2e3e21d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Organization_workspace/Titles exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49474011-f780-43d0-9354-e20aa40f3298</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fbe2735-51ad-44ad-8b74-be4d3aa30f7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>718ba0ef-b45f-4f5d-831e-3c7ee7626cb5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0550b84-6b57-4cc6-910d-8c0a7a6e2f87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Plan_Workspace/Credit Rules name exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b390810-939f-45af-9d7a-473e8c5d0fa9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a0525df-a0f0-4cca-8866-18e079ef41a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>395258b6-d2a9-4a3a-8c5a-c389d95ccb63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f67e2b2-5e5f-4db7-b066-95effa6c86ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Plan_Workspace/Deposit Rule exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dda6332-74ce-4380-a2aa-9e0bfa2fa6a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d35f863-0bf8-40dc-9701-ed64f5abd940</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85d000eb-e2f6-46ca-8366-97ac8f734206</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62c971f2-5a4b-44cc-b3ef-40726d7f5c3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Plan_Workspace/Incentive Rule exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>874e044a-6b8a-47e3-a73f-969584ea1008</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7a33acc-1015-4632-b88a-7d8b40ee8e83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>960fcc5a-ffe5-4fa2-92c1-380378c5cd11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a9ffcb2c-9964-445a-a7a0-77ffdbde1bb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Plan_Workspace/Measurement Rule exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a082e781-4ff4-45d2-a66c-735a9d7de0e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abfdd40a-ad25-4142-b1bb-8413fe6f9dd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4395c37-11bf-4522-9f1e-c1021aeeda74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>064097c2-d898-4ffc-8d4d-14e0479e714c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Plan_Workspace/Plan Components exist in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26cf5322-0bf8-43ef-8d7b-38c62b1bd93e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5b3b004-78ff-419b-9200-859739c7f1ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d379420a-ab47-436f-93ec-7ac07ac579e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9eb2b8d1-127f-4f58-ae55-ef449698d07a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Plan_Workspace/Plans exist in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9d19763-fd47-4401-ba6a-48164be9e254</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1ba00f1-d68c-41a4-aff6-1405ecd7d7f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c2fb284-c392-4a8f-81a9-3f2fc71dd125</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Security_workspace/Users exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8183ab6-111f-4b93-8fb2-8228398439fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7063cccb-de58-4489-b5ef-2d2d2d85e70c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d0dcbe0-df26-4ecb-af31-782309f5009c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
