<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c512f56f-0536-4025-bad3-e0c35d83c587</testSuiteGuid>
   <testCaseLink>
      <guid>653a256e-2551-4cba-ab42-4360b781282c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Commission Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>575bb085-19e1-48fc-bce4-1cadc716e45e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71b8cdc3-bad4-417a-90b6-bf06ba647473</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c8713f7-dfb4-494a-9ece-d447ec2cd517</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c349a562-59b5-44d5-b833-cd17085d1f21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Deposit Rule exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dda6332-74ce-4380-a2aa-9e0bfa2fa6a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d275f4cd-a2b7-414c-8012-4fc4481bcbe2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Earning Codes exist in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b3347e0-c28a-4478-a55d-5f4381a5f6fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc7c4630-eacb-4990-a271-e435b753e66a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Credit Rule(name of the Credit Rule) exists in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b390810-939f-45af-9d7a-473e8c5d0fa9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d7c3bcc-3e22-4491-9bd2-8f254c224617</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Earning Groups exist in the system</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9826086b-e4be-4ead-9095-4bbbb2f90117</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06871d47-08d0-4090-8435-24d167eae69b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Commission Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
