<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Relation_searchicon</name>
   <tag></tag>
   <elementGuidId>ee970702-9fb8-499a-9b1b-bd89ee758924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='commtree-search-btn'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='commtree-search-btn'][1]</value>
   </webElementProperties>
</WebElementEntity>
