<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calendar</name>
   <tag></tag>
   <elementGuidId>4f1b45ef-fbd5-4ba4-acb5-e27e4a39ae7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='app-subdiv']/a[@href='#/calendar/list']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='app-subdiv']/a[@href='#/calendar/list']</value>
   </webElementProperties>
</WebElementEntity>
