<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_FixedvalueVariable</name>
   <tag></tag>
   <elementGuidId>7ee3a8de-76b3-4855-9f1a-e866c8fa0c63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//option[@value='com.callidus.fixedvalue.FixedValue']</value>
   </webElementProperties>
</WebElementEntity>
