<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_LookupTableVariables</name>
   <tag></tag>
   <elementGuidId>1f88a604-f3dd-4bdb-9e96-912ba8e16a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//option[@value='com.callidus.mdlt.relational.impl.bean.RelationalMDLT']</value>
   </webElementProperties>
</WebElementEntity>
